
```{r figure_setup}
theme_update(
  axis.title.x = element_text(size = 12, angle = 0, hjust = .5, vjust = -0.3, face = "plain"),
  axis.title.y = element_text(size = 12, angle = 90, hjust = .5, vjust = .9, face = "plain"),

  axis.text.x = element_text(size = 10, angle = 0, hjust = .5, vjust = 1.5, face = "plain"),
  axis.text.y = element_text(size = 10, angle = 0, hjust = 1, vjust = 0, face = "plain"),

  axis.ticks = element_line(size = 0.3, linetype = "solid"),
  # axis.ticks = element_blank(),
  axis.ticks.length = unit(.15, "cm"),
  # axis.ticks.margin = unit(.1,'cm'),
  # axis.text = element_text(margin=unit(.1,'cm')),

  #--- legend ---#
  legend.text = element_text(size = 10, angle = 0, hjust = 0, vjust = 0, face = "plain"),
  legend.title = element_text(size = 10, angle = 0, hjust = 0, vjust = 0, face = "plain"),
  legend.key.size = unit(0.5, "cm"),

  #--- strip (for faceting) ---#
  strip.text = element_text(size = 10),

  #--- plot title ---#
  plot.title = element_text(family = "Times", face = "bold", size = 12),

  #--- margin ---#
  # plot.margin = margin(0, 0, 0, 0, "cm"),

  #--- panel ---#
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  panel.background = element_blank(),
  panel.border = element_rect(fill = NA)
)
```   

```{r blank-pic}
g_blank <- ggplot() +
  theme_void()

# ggsave(g_blank, file = "./Figure/blanc.pdf", height = 1)
```

```{r fig.id = "well-map-CO", cache = TRUE, fig.cap = "Spatial Distributions of Wells Used in Empirical Analysis", results = "hide", , fig.cap.style = "Image Caption"}
#/*=================================================*/
#' # Well Locations
#/*=================================================*/
# /*----------------------------------*/
#' ## State borders
# /*----------------------------------*/
CO_state <- st_read(dsn = here("Data"), "states") %>%
  dplyr::rename(name = STATE_NAME) %>%
  dplyr::filter(!(name %in% c("American Samoa", "Alaska", "Hawaii", "Puerto Rico", "Commonwealth of the Northern Mariana Islands"))) %>%
  dplyr::select(name) %>%
  st_transform(4269) %>%
  filter(., name == "Colorado") %>%
  mutate(name = as.character(name))

# /*----------------------------------*/
#' ## County sf
# /*----------------------------------*/
#--- CO counties ---#
CO_sf <- st_read(dsn = here("Data"), "Colorado_County_Boundaries") %>%
  st_transform(4269) %>%
  mutate(state = "Colorado") %>%
  dplyr::select(geometry, state, COUNTY)

# /*~~~~~~~~~~~~~~~~~~~~~~*/
#' ### CO wells
# /*~~~~~~~~~~~~~~~~~~~~~~*/
wells_loc_sf <- reg_data_CO %>%
  .[, .(wdid, REAname, latdecdeg, longdecdeg)] %>%
  unique(by = "wdid") %>%
  .[!is.na(latdecdeg), ] %>%
  .[!is.na(longdecdeg), ] %>%
  st_as_sf(coords = c("longdecdeg", "latdecdeg")) %>%
  st_set_crs(4269)

er_boundary <- st_read(here("Data/Electric_Retail_Service_Territories.shp")) %>%
  filter(STATE == "CO") %>%
  setnames(names(.), tolower(names(.))) %>%
  filter(holding_co == "HIGHLINE ELECTRIC ASSN" | holding_co == "Y-W ELECTRIC ASSN INC") %>%
  st_transform(4269)

# /*----------------------------------*/
#' ## Focus area
# /*----------------------------------*/
county_ls <- st_intersection(wells_loc_sf, CO_sf) %>%
  .$COUNTY %>%
  unique()

focus_CO_sf <- filter(CO_sf, COUNTY %in% county_ls) %>%
  mutate(State = "Colorado")

# /*----------------------------------*/
#' ## Map
# /*----------------------------------*/
#--- figure ---#
g_big <- ggplot() +
  geom_sf(data = CO_state, , fill = "NA", size = 1) +
  geom_sf(data = CO_sf, fill = "NA") +
  geom_sf(data = focus_CO_sf, fill = "gray") +
  theme(
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    #--- panel ---#
    panel.border = element_blank(),
    panel.grid.major = element_line(color = "transparent"),
    panel.grid.minor = element_line(color = "transparent"),
    panel.background = element_blank()
  )

g_small <- ggplot() +
  geom_sf(data = focus_CO_sf, alpha = 0.3) +
  geom_sf(data = wells_loc_sf, size = 0.5) +
  # geom_sf(data=wells_loc_sf,aes(shape=factor(REAname)),size=0.5) +
  # geom_sf(data=er_boundary,aes(color=holding_co),fill=NA,size=1) +
  ggsn::scalebar(st_buffer(focus_CO_sf, 0.1),
    location =
      "bottomleft", dist = 20, st.dist = 0.03, st.size = 3, dist_unit = "mi", transform = TRUE, model = "WGS84"
  ) +
  # scale_shape_discrete(name='Electricity Supplier') +
  theme(
    legend.positio = "bottom",
    axis.ticks.y = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_blank(),
    axis.title.y = element_blank(),
    axis.title.x = element_blank(),
    axis.line.x = element_blank(),
    axis.line.y = element_blank(),
    #--- panel ---#
    panel.border = element_blank(),
    panel.grid.major = element_line(color = "transparent"),
    panel.grid.minor = element_line(color = "transparent"),
    panel.background = element_blank()
  )

g_wel_loc <- ggplot() +
  coord_equal(xlim = c(0, 20), ylim = c(0, 20), expand = FALSE) +
  annotation_custom(ggplotGrob(g_small),
    xmin = 5, xmax = 20, ymin = 0,
    ymax = 20
  ) +
  annotation_custom(ggplotGrob(g_big),
    xmin = 0, xmax = 7, ymin = 8,
    ymax = 18
  ) +
  geom_segment(aes(x = 6.8, y = 14.5, xend = 8.5, yend = 14),
    arrow = arrow(length = unit(0.30, "cm")), lineend = "round", size = 0.5
  ) +
  theme_void()

# ggsave(g_wel_loc, file = here("Figures/well_loc.pdf"), height = 5.583, width = 5.583)

# ggsave(g_wel_loc, file = "./Figures/well_loc.eps", height = 5.583, width = 5.583, device = "eps")

g_wel_loc

```

`r run_pagebreak()`

```{r fig.id = "etw-pc-gpm", cache = TRUE, fig.cap = "Heterogeneity of Energy Use Efficiency and Pumping Costs (All Years)", results = "hide"}
#/*=================================================*/
#' # Energy use efficiency
#/*=================================================*/
plot_wtq_pc_CO <- reg_data_CO[, .(etw, pc, gpm)] %>%
  .[, etw := etw / 12]

g_fig_etw <- ggplot(data = plot_wtq_pc_CO[etw < 140, ]) +
  geom_histogram(aes(x = etw), color = "black", alpha = 0.3) +
  xlab("Energy Use Efficiency (kwh/acre-inch)") +
  ylab("") +
  theme(
    strip.text.x = element_text(margin = margin(0.15, 0, 0.15, 0, "cm")),
    axis.line.x = element_blank(),
    axis.line.y = element_blank()
  )

g_fig_pc <- ggplot(data = plot_wtq_pc_CO[etw < 140, ]) +
  geom_histogram(aes(x = pc), color = "black", alpha = 0.3) +
  xlab("Pumping Costs ($/acre-inch)") +
  ylab("") +
  theme(
    strip.text.x = element_text(margin = margin(0.15, 0, 0.15, 0, "cm")),
    axis.line.x = element_blank(),
    axis.line.y = element_blank()
  )

g_fig_gpm <- ggplot(data = plot_wtq_pc_CO) +
  geom_histogram(aes(x = gpm), color = "black", alpha = 0.3) +
  xlab("Well Yield (gallons per minute)") +
  ylab("") +
  theme(
    strip.text.x = element_text(margin = margin(0.15, 0, 0.15, 0, "cm")),
    axis.line.x = element_blank(),
    axis.line.y = element_blank()
  )

g_etw_pc_gpm <- g_fig_etw / g_fig_pc / g_fig_gpm + 
  plot_annotation(
    tag_levels = list("a", "1"),
    tag_prefix = '(',
    tag_suffix = ')'
  )

# ggsave(g_etw_pc_gpm, file = here("Figures/etw_pc_gpm.pdf"), height = 5.583, width = 5.583)

g_etw_pc_gpm

```

Note: This figure presents the distribution of energy use efficiency, pumping costs, and well yield for all the observed years.

`r run_pagebreak()`

```{r fig.id = "af-wy", fig.cap = "The relationship between water use and well yield", results = "hide"}
#/*=================================================*/
#' # Impacts of well yield on water use
#/*=================================================*/
plot_data_CO <- reg_data_CO[, .(water_use, gpm, year)] %>%
  .[, type := "Colorado"] %>%
  .[water_use < 1000, ] %>%
  .[gpm < 2000, ] %>%
  .[water_use < 760, ] %>%
  .[water_use > 20, ] %>%
  .[!(water_use > 600 & year == 2016), ] %>%
  .[!(water_use < 30 & year == 2013), ]

g_af_wy <- ggplot(data = plot_data_CO[water_use < 1000, ]) +
  geom_point(aes(y = water_use, x = gpm), size = 0.4, color = "#808080") +
  geom_smooth(aes(y = water_use, x = gpm), method = "lm", color = "black") +
  facet_wrap(year ~ .) +
  xlab("Well Yield (gpm)") +
  ylab("Water Use (acre-feet)")

# ggsave(g_af_wy, file = here("Figures/water_well_yield.pdf"), height = 5.583, width = 5.583)

# ggsave(g_af_wy, file = "./Figures/water_well_yield.eps", height = 5.583, width = 5.583)

g_af_wy
```

```{r fig.id = "pc-vs-wy", fig.cap = "The relationship between pumping cost and well yield", results = "hide"}
#/*=================================================*/
#' # Pumping costs vs. well yield
#/*=================================================*/
# plot_data_NE <- reg_data_NE[,.(w_pc,w_gpm)] %>%
#   .[,type:='Nebraska']

# plot_data_CO <- reg_data_CO[, .(w_pc, w_gpm)] %>%
#   .[, type := "Colorado"] %>%
#   .[w_pc > -2, ]

# g_pc_wy <- copy(plot_data_CO) %>%
#   .[, type := factor(type, levels = c("Nebraska", "Colorado"))] %>%
#   ggplot(data = .) +
#   geom_point(aes(y = w_pc, x = w_gpm), size = 0.3, color = "#808080") +
#   geom_smooth(aes(y = w_pc, x = w_gpm), method = "lm", color = "black") +
#   # facet_wrap(type~.,scales = "free",ncol=1) +
#   xlab("Within-transformed Well Yield (gpm)") +
#   ylab("Within-transformed Pumping Costs ($/acre-inch)")

# ggsave(g_pc_wy, file = here("Figures/pc_wy.pdf"), height = 3.5, width = 5.583)
# # ggsave(g_pc_wy, file = "./Figures/pc_wy.eps", height = 3.5, width = 5.583)

# g_blank

```

